apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1
  labels:
    app: frontend-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-1
  template:
    metadata:
      labels:
        app: frontend-1
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080
